version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: "Lint the code"
          command: |
            npm install --loglevel error --only dev
            ./node_modules/.bin/eslint .

      - run:
          name: "Update Docker"
          command: |
            # There's need to update docker if we aren't deploying
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker version
              sudo service docker stop
              curl -fsSL https://get.docker.com/ | sudo sh
            fi
      - run: docker version

      # Clean up after linting and testing e.g. remove node_modules/
      # so test packages aren't included in any production images
      - deploy:
          name: "Clean up linting and test files"
          command: |
            git clean -fxd
            git reset --hard

      - deploy:
          name: "Build docker image and release"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              git config --global user.email "ci@fnproject.com"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              ./release.sh
            fi
